### ISSUE TITLE
Organisera Backend

### ISSUE THREAD

**Issue by Tenkaklet** [Tenkaklet/coderdojo#1]
Hur ska det hela fungera?
- express applikation tänker jag?

**Comment by thohell** [comment]
Vi behöver i princip svar på ett antal frågor, så kan man skissa på en arkitektur. Men express är ju enkelt och smidigt för de flesta use cases.

## Frågor
- Vad ska appen _göra_?
  - Den bollen har Oscar, som jag uppfattar det?
- API frontend <-> backend?
  - Lämpligast är troligen rest/json, om vi inte har andra krav.
- Datalager?
  - Beror helt på vad appen ska göra. Kan vara enkelt och smalt, eller stort och tjockt :)

**Comment by Tenkaklet** [comment]
Bra frågor som vi bör rätta till.
Vi använder de idéer och figma för idéer. Vi skriver i Discord för konversationen.

**Comment by Oskar-Sjoberg-dev** [comment]
> ## Frågor
> * Vad ska appen _göra_?

>   * Den bollen har Oskar, som jag uppfattar det? (Se issue [Google Doc med Idéer #3](https://github.com/Tenkaklet/coderdojo/issues/3))

Nej alla får ha idéer.  Skriv gärna allt du kan komma på för min del :)  Det var bara jag som klantade till det lite med dokumentet tidigare.

**Comment by Tenkaklet** [comment]
@thohell @asili2001 Har snackat ihop sig.
