### ISSUE TITLE
Gör Discussions fungerande

### ISSUE THREAD

**Issue by Tenkaklet** [Tenkaklet/coderdojo#11]
- allmän info
- Rösta fram olika saker
- Kunna föra idéer och enhancements

**Comment by Tenkaklet** [comment]
Hur @Oskar-Sjoberg-dev lägger vi upp på bästa sätt?

**Comment by Oskar-Sjoberg-dev** [comment]
bra fråga Jag skapade två olika pages på Wiki för updates och en till för om allmänt vad vi sysslar med/annat.

om vi skulle vilja kan man ju lägga up en enbart för diskussion om vi inte har det i sysslar med pagen.

alternativt, beroende på hur fullt det blir i pages så kan man skapa separat för front och back end. med samma upplägg tänker jag.

**Comment by Tenkaklet** [comment]
Smart. Då kanske fördela upp sidor till frontend och end backend?

**Comment by Oskar-Sjoberg-dev** [comment]
> Smart. Då kanske fördela upp sidor till frontend och end backend?

Har fixat 5 olika pages för updates/diskussion, front/backend och en generell. känns upplägget bra eller har vi några önskemål? :)

**Comment by Tenkaklet** [comment]
Gör en Generell Wiki också.
Wiki är offentligt för alla att läsa utanför vår collaborators. Så en bra Generell "Hej och därför gör vi detta!" Intro sida hade varit nice. Vad tycker ni?

**Comment by Tenkaklet** [comment]
Jag gör en Generell Wiki och så kan du @Oskar-Sjoberg-dev bygga på det :)
