### ISSUE TITLE
Sätt upp DevOps flöde för development branch.

### ISSUE THREAD

**Issue by thohell** [Tenkaklet/coderdojo#25]
Sätt upp github flöde devops deployment från development branch.

**Comment by Tenkaklet** [comment]
Vi avvaktar tills vi har allt lokalt.

**Comment by asili2001** [comment]
@thohell @Tenkaklet Bästa sättet att arbeta med PHP i backend har vi kommit fram till att Det är bättre att jag pushar koden direkt i dev api och därför tycker jag att dev ops flöde för dev branch är en mycket bra ide.

**Comment by Tenkaklet** [comment]
Hur ser det ut för dig imorgon @thohell för att samla ihop en bra plan för detta?

**Comment by Tenkaklet** [comment]
Jag tar bort denna som milestone så vi är on track.
