### ISSUE TITLE
Google Doc med Idéer

### ISSUE THREAD

**Issue by Tenkaklet** [Tenkaklet/coderdojo#3]
lägg länken till google doc under denna kommentar:

[länk till Google Doc](https://docs.google.com/document/d/1MZdMYhdVADqQ6i0IOfie5hpiahxI6YhZOstFgoQWHPA/edit)

**Comment by Oskar-Sjoberg-dev** [comment]
https://docs.google.com/document/d/1MZdMYhdVADqQ6i0IOfie5hpiahxI6YhZOstFgoQWHPA/edit?usp=sharing

Google Doc som ska vara tillgängligt för alla som klickar på den :)

// Har samlat lite av idéerna som jag sett i discord.

**Comment by Tenkaklet** [comment]
Toppen! Gör den så man kan skriva också.

**Comment by Tenkaklet** [comment]
Detta är rätt. Det är fixat. Jag stänger detta issue. Bra jobbat Oscar!
