### ISSUE TITLE
Figma länk.

### ISSUE THREAD

**Issue by Tenkaklet** [Tenkaklet/coderdojo#6]
ska vara i delbar format.

**Comment by Tenkaklet** [comment]
Hej,
är det denna länk @Louna-Skylander [Länk](https://www.figma.com/file/JNDQGH7JIVIC854SZPhk20/coderdojo-ukraine?node-id=0%3A1)?

**Comment by Louna-Skylander** [comment]
Stämmer.

https://www.figma.com/file/JNDQGH7JIVIC854SZPhk20/coderdojo-ukraine?node-id=0%3A1

**Comment by Tenkaklet** [comment]
Toppen!

**Comment by Tenkaklet** [comment]
Stänger och lägger in denna i done!
